### ISSUE TITLE
Erro ao não digitar um cpf numérico

### ISSUE THREAD

**Issue by BMasquio** [alerj/parlamentojuvenil#203]
![image](https://user-images.githubusercontent.com/15174854/57539817-b045f300-7321-11e9-860e-b7f06de750be.png)

[2019-05-10 12:45:49] local.ERROR: ErrorException: A non-numeric value encountered in /Users/brunomasquio/code/parlamentojuvenil/vendor/jailtonsc/validador-cpf-laravel/src/Validation/CpfValidation.php:78
Stack trace:
#0 /Users/brunomasquio/code/parlamentojuvenil/vendor/jailtonsc/validador-cpf-laravel/src/Validation/CpfValidation.php(78): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'A non-numeric v...', '/Users/brunomas...', 78, Array)
#1 /Users/brunomasquio/code/parlamentojuvenil/vendor/jailtonsc/validador-cpf-laravel/src/Validation/CpfValidation.php(170): ValidadorCpf\Validation\CpfValidation->calc_digitos_posicoes('f')

**Comment by BMasquio** [comment]
Feito
